### ISSUE TITLE
Allow specific users to send email from any address

### ISSUE THREAD

**Issue by pirate** [Mailu/Mailu#1096]
Before switching to Mailu I had postfix set up so that my admin user `admin@mydomain.dev` could impersonate / send email as any other user.

This was extremely useful for sending email programmatically from multiple sources, e.g. from a web app that needs to send email from `*@mydomain.dev` and several other domains like `*@admin.mydomain.dev`/`*@someotherdomain.dev`.

I suspect I can add something into `overrides/postfix.conf` to get this behavior back, but I'm not sure how to do it since I only want a specific user to be able to impersonate others, not all users.  Ideally there would be a UI page to configure the permitted sender addresses for each user, with sqlite-style wildcard support.

```ini
smtpd_client_restrictions =
  permit_mynetworks,
  check_sender_access ${podop}senderaccess,
  reject_non_fqdn_sender,
  reject_unknown_sender_domain,
  reject_unknown_recipient_domain,
  reject_unverified_recipient,
  permit

smtpd_relay_restrictions =
  permit_mynetworks,
  permit_sasl_authenticated,
  reject_unauth_destination
```

For now, given I'm the only one using the server and I need this behavior back ASAP, can I just remove the `check_sender_access ${podop}senderaccess,` line? Or is there a better long-term fix?

I also cant just use `RELAYNETS` with some whitelisted IPs becuase the servers doing the sending have dynamic IP addresses that often change, I need it to be whitelisted on a per-user basis not a per-sender-ip basis.

**Useful links:**
- https://github.com/Mailu/Mailu/blob/master/core/postfix/conf/main.cf
- http://www.postfix.org/ADDRESS_VERIFICATION_README.html
- http://www.postfix.org/postconf.5.html#check_sender_access

**Comment by kaiyou** [comment]
Using relaynets is probably better advised, since removing sender access will also allow illegitimate impersonation from anywhere, even external scammers.

Then, depending on your setup you could use aliases: a user can impersonate any alias that points to its address. Otherwise we will need to implement this while it is not entirely trivial: sender access verifications do not pass the authenticated user to the background.

**Comment by pirate** [comment]
Wait but isn't it all authenticated with the SMTP credentials?  How would a spammer be able to send from anywhere if they don't have SMTP credentials for the server?

All registered user accounts on this server are trusted, it's just me and a couple other people, so there's no chance of users that have SMTP credentials / registered accounts being spammers. I just want to authorize a single SMTP user/pass to be able to send from `%@mydomain.com`.

I tried the alias setup you suggested, the problem is that the alias for `%@mydomain.com` that allows it to send from any address conflicts with other accounts and becomes a catch-all for received mail, I just want to allow sending without changing the received mail routing.

> I also cant just use RELAYNETS with some whitelisted IPs becuase the servers doing the sending have dynamic IP addresses that often change.

**Comment by kaiyou** [comment]
Incoming mail using is not authenticated: SMTP only supports authenticating local users, remote users aren't. And sender access is the set of rules that makes sure that remote servers cannot impersonate your local users, among other things.

**Comment by pirate** [comment]
Right, I know incoming mail isn't authenticated, I meant for outgoing mail.

> makes sure that remote servers cannot impersonate your local users, among other things.

This is exactly what I'm trying to accomplish, I need my servers to be able to send from `*@allmydomains.com` using one set of SMTP credentials.  

I already tried the catchall, it didn't work, all relayed emails got rejected due to sender addresses not being owned by the SMTP user.

**Comment by pirate** [comment]
I figured it out using overrides.  For anyone else trying to do this, here's the full config I ended up with.  This config will allow a specific user admin@mydomain.com to send mail from *@*, and as an example I added a slightly more limited admin@otherdomain.com user that can only send from any *@otherdomain.com address.  I also added a third domain that has all `@yetanotherdomain.com` mail relayed via mailgun instead of being processed locally.

**`data/overrides/postfix.cf`**
```
# Relatively lax restrictions on sending (only secure if all sasl users are trusted, do not use with mailservers that have open registration)
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination
smtpd_sender_login_maps = pcre:/overrides/sender_logins, socketmap:unix:/tmp/podop.socket:senderlogin
sender_dependent_relayhost_maps = texthash:/overrides/relay_hosts
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = texthash:/overrides/sasl_passwd
```

**`data/overrides/sender_logins`:**
```
# Authorize only the admin@mydomain.com smtp user to send from any address on any domain
/.*/                                          admin@mydomain.com
# Authorize the admin@otherdomain.com user to send from any @otherdomain.com address
/.^*@otherdomain.com/     admin@otherdomain.com
```

**`data/overrides/relay_hosts`:**
```
# Any mail sent from @yetanotherdomain.com gets relayed via mailgun instead of being handled locally
@yetanotherdomain.com          [smtp.mailgun.org]:587
```

**`data/overrides/sasl_passwd`:**
```
# credentials to use for mailgun smtp relay
[smtp.mailgun.org]:587 postmaster@yetanotherdomain.com:mailgunpasswordhere
```

**Comment by micw** [comment]
This should probably done at the admin service because it delivers the list of allowed "from" addresses to postfix.

**Comment by fracture-point** [comment]
I would also love to see this feature, as this is a key requirement of working with Owncloud/Nextcloud (the Owncloud server needs to be able to log in to Mailu and send email on behalf of many Mailu users).

**Comment by fracture-point** [comment]
@pirate I tried your solution and was not able to get it to work.  Firstly I put these in the ```overrides``` folder (not under ```/data/overrides```, which did not work at all).  

When I make your above changes, I am able to send from my admin email as any other email on the server, however, I cannot send as a "normal" user anymore, sending as themself.  I get this error:

```
smtp_1 | Feb 06 22:30:47 mail2 postfix/smtpd[194]: NOQUEUE: reject: RCPT from mailu_webmail_1.mailu_default[xxx.xxx.xxx.xxx]: 553 5.7.1 <user@domain.com>: Sender address rejected: not owned by user user@domain.com; from=<user@domain.com> to=<receiver@outsidedomain.com> proto=ESMTP helo=<multimail.work>
```
where user@domain.com is a standard user, sending mail as themself.

I am not using the optional configs in your suggestions; perhaps some lines need to be removed from ```overrides/postfix.cf```?  I'm not overly familiar with the overrides file, so I didn't want to blindly start trying changes...

**Comment by jheinitz** [comment]
Hello!

I'm struggleing as well. I love to setup one or two users that are able to send as every user, but all other users should send email using their own email adress. When I add the settings in override, I can achieve that I can send emails from my website through PHP using a different sender adress, but when I use the integrated rainloop, I cannot send mails. The error is this:

` postfix/smtpd[131]: NOQUEUE: reject: RCPT from mailu_webmail_1.mailu_default[192.168.203.11]: 553 5.7.1 <admin@example.de>: Sender address rejected: not owned by user admin@example.de; from=<admin@example.de> to=<jens@example.de> proto=ESMTP helo=<test.example.de>`

@pirate, I guess, I'm facing the same issue as @fracture-point does.

Any ideas?

Best regards

Jens

**Comment by pirate** [comment]
Strange... can you post your exact config used in `overrides/*`?

**Comment by jheinitz** [comment]
Sure. Here are my files:
**postfix.cf:**
`$ cat postfix.cf
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination
smtpd_sender_login_maps = pcre:/overrides/sender_logins, socketmap:unix:/tmp/podop.socket:senderlogin
sender_dependent_relayhost_maps = texthash:/overrides/relay_hosts
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = texthash:/overrides/sasl_passwd`

**sender_logins:**
`$ cat sender_logins
/.*/                      jens@example.de`

The files **relay_hosts** and **sasl_passwd** are empty, because I only want to have this single mail address "jens@example.de" to be able to send mails from every address wehile all other should only be able to send through their own address.

Thanks and best regards

Jens

**Comment by pirate** [comment]
Try adding this to make sure you can log in as `jens@example.de` from anywhere:

**`postfix.cf`:**
```diff
+smtpd_client_restrictions = permit_mynetworks, permit
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination
smtpd_sender_login_maps = pcre:/overrides/sender_logins, socketmap:unix:/tmp/podop.socket:senderlogin
...
```

**Comment by pirate** [comment]
After much head-scratching, I think I found the answer. Postfix defines a "match" when searching `sender_login_maps` as any lookup that succeeds, but the *result* of that lookup is not considered.

**`tl; dr`: If you intend to use a *union* of the results from all mappings in `smtpd_sender_login_maps`, instead of just taking the *first* succeeding lookup result, the mappings must be combined somehow (e.g. via SQL `UNION` or `unionmap`).**

At its core, it's a surprisingly simple problem caused by Postfix's short-circuiting behavior when doing mapping lookups. Buckle up for the ride, this is a long answer...

---

## Background

From the Postfix documentation on sender login maps:

> **smtpd_sender_login_maps** (default: empty)
>     ...
> 
>   Specify zero or more "type:name" lookup tables, separated by whitespace or comma.  
>  *Tables will be searched in the specified order until a match is found.*

http://www.postfix.org/postconf.5.html#smtpd_sender_login_maps

The purpose of using `smtpd_sender_login_maps` is to validate whether the currently authenticated SMTP user is allowed to send from a given FROM address in their message. It's a powerful feature to restrict the addresses a client can send from based on who the authenticated SMTP user is.

**`smtpd_sender_login_maps` has many use cases, e.g.:**

- Prevent a user from logging in and sending a message as someone else  
    *> Bob can send as `bob@example.com`, but can't send as `alice@example.com`*

- Allow multiple users to send from a single shared address neither of them own  
    *> Bob and Alice can both send as `marketing@example.com`*

- Allow a single user to send from multiple addresses they own  
    *> Alice can send as both `alice@example.com` and `alice.smith@example.com`*

- Allow an admin to send messages from many addresses (even owned by others)  
    *> Tracy, the IT admin can send as anyone `.*@example.com`*

- And more... (remember, lookups can be via TCP socket, SQL query, regex, etc.)

---

## Example Scenario

We're going to investigate this use-case in particular:

> - Allow an admin to send messages from many addresses (even owned by others)  
>    *> Tracy, the IT admin can send as anyone `.*@example.com`*

Imagine a setup where we have Postfix and MySQL running on a mailserver.
There are 3 users stored in the DB who can authenticate via SMTP with postfix:

- `alice@example.com`: can only send from `alice@example.com`,`alice.smith@example.com`
- `bob@example.com`: can only send from `bob@example.com`,`bob.jones@example.com`
- `admin@example.com`: should be able to send from *any* `.*@example.com` address

Regular users can only send from their main address and their aliases, but we want to allow the admin to be able to masquerade as *any* sender without restrictions. In real life, this type of setup is useful whenever a user needs to be able to send from many addresses `.*@example.com` using only one SMTP login (e.g. if the addresses are dynamically-generated or belong to other users).

The normal approach is to use `smtpd_sender_login_maps` to achieve this setup.

> ### Example Config
> **`/etc/postfix/main.cf`:**
>    ```ini
>    ...
>    
>    smtpd_sender_login_maps = 
>        mysql:/etc/postfix/sender_logins.cf,
>        pcre:/etc/postfix/sender_overrides.cf
>        
>    ...
>    ```
>
> MySQL is checked first, then the pcre is checked only if the mysql lookup returned 0 results.
>
>---
> **`/etc/postfix/sender_logins.cf` (`mysql`):**
>    ```ini
>    hosts = 127.0.0.1
>    user = postfix
>    password = yourDatabasePasswordHere
>    dbname = mail
>    query = SELECT email FROM users WHERE email='%s'
>    ```
>
> This mapping checks the DB and returns the normal SMTP user for a given FROM addr, e.g.:  
>   `alice@example.com         -> alice@example.com`  
>   `bob.jones@example.com     -> bob@example.com`  
>
>---
> **`/etc/postfix/sender_overrides.cf` (`pcre`):**
>    ```ini
>    /.*@example.com/     admin@example.com
>    ```
>
> This mapping matches *all* `@example.com` FROM addrs and returns the admin SMTP user, e.g.:  
>   `.*@example.com -> admin@example.com`  


---

## The problem

**The behavior the user expects:**

1. Postfix looks up the FROM addr in the first `sender_login_maps` db
2. it finds a matching entry for the FROM addr
3. the returned SMTP user != logged in user, **so we try the next mapping db**
4. Postfix looks up the FROM addr in the next `sender_login_maps` db
5. it finds a matching entry for the FROM addr
6. the SMTP user == logged in user
7. **Postfix sends the message succesfully**

**What actually happens:**

1. Postfix looks up the FROM addr in the first `sender_login_maps` db
2. it finds a matching entry for the FROM addr, **so the lookup process stops**
3. the returned SMTP user != logged in user
4. **Postfix rejects the message**

---

## Explanation

The issue is that Postfix doesn't check both mappings and merge the results, instead it stops the lookup process the moment it encounters the *first* matching lookup returning any SMTP user.

If the returned SMTP user doesn't match the currently authed user, it won't proceed to lookup the address in the next database, it'll just immediately `DENY`.

The same lookup conflict can happen with any two mappings that share keys, e.g. two mysql databases `mysql:...,mysql:...`, not necessarily just a `pcre` with `/.*/` or `/.*@example.com/`. Any exact match or wildcard match like `@example.com  someuser@example.com` in the first mapping will take precedence and prevent the second mapping from being queried at all.

### Scenario 1: `alice@example.com` tries to send from `alice@example.com`

✅ This works fine, the email is sent because the address matches the sender as expected.

1. `alice@example.com` logs in via SMTP to send a msg from `alice@example.com`
2. `alice@example.com` lookup in `smtpd_sender_login_maps` returns `alice@example.com`
3. Sending succeeds, `alice@example.com` == SMTP authed user `alice@example.com`

### Scenario 2: `admin@example.com` tries to send from `alice@example.com`

❌ This does not work, the email is rejected because the SMTP authed user `admin@example.com` doesn't match the first lookup result `alice@example.com`.

1. `admin@example.com` logs in via SMTP to send a msg from `alice@example.com`
2. `alice@example.com` lookup in `smtpd_sender_login_maps` returns `alice@example.com`
3. Sending fails, `alice@example.com` != SMTP authed user `admin@example.com`  
    `postfix/smtpd[16645]: NOQUEUE: reject: RCPT from webmail.mailserver[192.168.1.5]: 553 5.7.1 <alice@example.com>: Sender address rejected: not owned by user admin@example.com; from=<alice@example.com> to=<bob@example.com> proto=ESMTP helo=<mail.example.com>`

### What if we flip the order of the mappings?

```ini
smtpd_sender_login_maps = 
    pcre:...,        # moving the pcre mapping above mysql makes it worse
    mysql:...
```

Flipping the order of the mappings so that the pcre file is checked before mysql won't fix the problem. It even makes it worse because the catchall `.*@example.com` will overshadow all the real users in MySQL and prevent any user other than `admin@example.com` from sending email.

When it looks up `alice@example.com` in the pcre file, it returns `admin@example.com` as the only allowed user and fails before it ever checks the mysql database.

---

## The solutions

### A. Make the `smtpd_sender_login_maps` disjoint

If the mappings don't contain any overlap in keys, then the order doesn't matter, and any lookup that doesn't match the first db will proceed to check the subsequent ones as expected.

Mappings earlier in the list cannot have any "catchall" or wildcard keys or they will match everything and overshadow results from later mappings. 

### B. Join multiple lookup results in SQL with `UNION`

If you're using the `mysql` table type for your `smtpd_sender_login_maps` mappings, then you can control the SQL query run when doing an address lookup and you may be able to join multiple mappings at the SQL level. 

Assuming all your mappings are accessible in the same MySQL database, you can concatenante the results of multiple address lookups at the SQL level using a `UNION` statement like so:

`main.cf`:

    smtpd_sender_login_maps = mysql:/etc/postfix/sender_logins.cf

`sender_logins.cf`:

    hosts = 127.0.0.1
    user = postfix
    password = yourDatabasePasswordHere
    dbname = mail
    query = SELECT email
                FROM users
                WHERE email='%s'
            UNION SELECT destination
                FROM aliases
                WHERE source='%s'
            UNION SELECT email
                FROM users
                WHERE wildcard_sending=1

In this example we would set `admin@example.com` to have `wildcard_sending=1` in SQL, and then it would be returned with every lookup result along with the normal user and alias matches, e.g.

    alice.smith@example.com    -> alice@example.com,admin@example.com
    bob@example.com            -> bob@example.com,admin@example.com

### C. Use `unionmap` to combine multiple mappings

If you're using Postfix 3.0 or above, you might be able to try using the new `unionmap` feature, which performs a lookup to all the mappings at once and concatenates the results together.

    smtpd_sender_login_maps = unionmap:{
            mysql:/etc/postfix/sender_logins.cf,
            pcre:/etc/postfix/sender_overrides.cf }

With this setup, the mysql results will be concatenated with the pcre lookup results, e.g.

    alice.smith@example.com    -> alice@example.com,admin@example.com
    bob@example.com            -> bob@example.com,admin@example.com

See http://www.postfix.org/DATABASE_README.html#types **unionmap** for more info.

---

## Sources

> Word "match" is thus to be taken here in the narrowest sense: just a
> matching  address, not a matching (address, login name) pair.
> Moreover, when a matching  address is found, the lookup chain is
> immediately halted with a binary  reject/accept decision.

- https://www.mail-archive.com/postfix-devel@postfix.org/msg00677.html  
  (I highly recommend reading this entire mailing list thread for more context)
- http://www.postfix.org/postconf.5.html#smtpd_sender_login_maps
- http://www.postfix.org/SMTPD_ACCESS_README.html#lists
- http://www.postfix.org/DATABASE_README.html#types
- http://www.postfix.org/access.5.html
- https://unix.stackexchange.com/questions/294300/postfix-prevent-users-from-changing-the-real-e-mail-address
- https://groups.google.com/forum/#!topic/mailing.postfix.users/X7Wj_nSEyKI
- https://workaround.org/ispmail/jessie/relaying-smtp-authentication

**Comment by pirate** [comment]
So the actual solution for the Mailu use-case is a one-line fix:

**`overrides/postfix.cf`:**
```ini
...
smtpd_sender_login_maps = unionmap:{socketmap:unix:/tmp/podop.socket:senderlogin, pcre:/overrides/sender_logins}
...
```

I just deployed it on my Mailu server and confirm it works, regular users are able to send as themselves and their aliases, and admins are able to send as everyone. 😄

**Comment by jheinitz** [comment]
Moin pirate.

Thanks for the detailed explanation. I just deployed the change on my server and I can confirm that it works perfectly. Sometimes it is worth to dig a little bit deeper into the documentation. 

Again, thank you so much for solving this issue. 

Best regards 

Jens

**Comment by matzrm** [comment]
Thank you so much!! 
I have used your instructions to configure Odoo v13 to works with mailu. And works great!

**Comment by Nebukadneza** [comment]
Sorry for grabbing this up again from the dead …
… but @pirate — your works seems really helpful to a lot of users out there. Currently, I don’t see we have the resources to implement this as a full-blown feature (which would need UI, database, integration into podop, postfix, etc), especially given the initial concerns given by @kaiyou (that i share).
Your workaround on the other hand is lean and easy to understand.

Would you care to add this to the documentation? That way, other users can more easily profit from this ….

Thanks a bunch regardless of what you’ll decide ^_^

**Comment by pirate** [comment]
Thanks! I'm fine with adding it to a docs file or wiki somewhere, no point building UI and db, etc. unless there's bigger demand.
One question though, can you or @kaiyou clarify this part:

> Using relaynets is probably better advised, since removing sender access will also allow illegitimate impersonation from anywhere, even external scammers

So far on my server it seems like smtpd clients are only able to send arbitrary mail if they are the (Mailu password authenticated) admin user. Regular mailu users (and external clients) remain restricted to sending from only addresses they own. I'm definitely curious, because I don't want spoofed sender relaying happening on my servers, and because I want to make sure the docs are accurate with non-harmful/secure defaults in the examples.

**Comment by fracture-point** [comment]
Wonderful, thanks @pirate , that did the trick.  Here's what I've added to my deployment script, which would be run during the install/migration:

```
cat > /mailu/overrides/postfix.cf <<'endmsg'
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination
smtpd_sender_login_maps = unionmap:{socketmap:unix:/tmp/podop.socket:senderlogin, pcre:/overrides/sender_logins}
sender_dependent_relayhost_maps = texthash:/overrides/relay_hosts
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = texthash:/overrides/sasl_passwd
endmsg

cat >  /mailu/overrides/sender_logins <<'endmsg'
/.*/                      CHANGEME@CHANGEME.COM
endmsg

touch /mailu/overrides/relay_hosts
touch /mailu/overrides/sasl_passwd
```

**Comment by rabauss** [comment]
Thanks for this issue, but unfortunately I still get the following error:
`reject: RCPT from unknown[10.0.0.2]: 553 5.7.1 <no-reply@xxx>: Sender address rejected: not owned by user admin@xxx`

Does anyone know what could be the problem?

**Comment by pirate** [comment]
Can you post your verbatim configs (with passwords and hostnames redacted) @rabauss?

**Comment by rabauss** [comment]
settings are like @fracture-point mentioned:

```
//overrides/postfix.cf
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination
smtpd_sender_login_maps = unionmap:{socketmap:unix:/tmp/podop.socket:senderlogin, pcre:/overrides/sender_logins}
sender_dependent_relayhost_maps = texthash:/overrides/relay_hosts
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = texthash:/overrides/sasl_passwd
```

```
//overrides/sender_logins
/.*/                   admin@xxx
```
empty files `overrides/sasl_passwd` + `overrides/relay_hosts`

**Comment by benyanke** [comment]
I'd also really like to be able to use this, and relaynets aren't what I need - I need something which can use some admin credentials, from any network, and send a notification from *@mydomain.com. Especially for people without a static IP, relaynets aren't useful.

Is this planned to be added to the gui, or is it still an edit in a config file?

**Comment by fracture-point** [comment]
This might sound odd, but upon further investigation it would appear that only the first line in `/overrides/sender_logins` is getting parsed?  If I have two lines, the account on the 2nd line gets a "Sender address rejected" when sending as a different account.  1st line works fine, and if I switch the order, the 1st line continues to be observed properly and the 2nd line is not.  🤔Not sure if there is a syntax here around spacings/tabs, etc. but I've tried both, and I've also tried with/without a blank line at the end of the file.

**Comment by pirate** [comment]
Can you post your `sender_logins` file (redacted) @fracture-point, it may be due to overlapping regexes?  You could also try create a whole other `pcre` file and adding it to the `unionmap: {...}` list.

**Comment by fracture-point** [comment]
Okay so maybe that's the problem - I have `sender_logins` currently configured with two "cross-domain admins" as such:

```
/.*/                      user1@domain1.com
/.*/                      user2@domain2.com
```

If this is improper, how might I accomplish having 2 such accounts?

**Comment by pirate** [comment]
Yeah that won't work, the first regex will match everything and the second one will never be checked.  Create a 2nd file containing only the 2nd line and add it to the unionmap list.

**Comment by fracture-point** [comment]
A little bit clunky, but that works!  Thank you @pirate.

**Comment by rabauss** [comment]
Oh I guess, that was my problem as well :-/

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by benyanke** [comment]
Not stale

**Comment by clopnis** [comment]
Hello,
I did it by an other simplest way.
The restriction is here  : reject_authenticated_sender_login_mismatch
`
# Internal SMTP service                                                                                                                                                                       
10025     inet  n       -       n       -       -       smtpd                                                                                                                                 
  -o smtpd_sasl_auth_enable=yes                                                                                                                                                               
  -o smtpd_client_restrictions=reject_unlisted_sender,**reject_authenticated_sender_login_mismatch**,permit                                                                                       
  -o smtpd_reject_unlisted_recipient=no                                                                                                                                                       
  -o cleanup_service_name=outclean
`

So I did a quick overrides/postfix.master
`
10025/inet=10025      inet  n       -       n       -       -       smtpd -o smtpd_sasl_auth_enable=yes -o smtpd_client_restrictions=reject_unlisted_sender,permit -o smtpd_reject_unlisted_recipient=no -o cleanup_service_name=outclean
`
My 2 cents
Cyril

**Comment by pirate** [comment]
Unless I'm mistaken, I believe this opens up your server to allow any authed user to send from any address @clopnis. This is less granular (and potentially more dangerous) than the other solution, which only allows *specific* senders to send from *specific* patterns (which could be `*@*`, but don't have to be, e.g. you could only allow sending from `bot-*@example.com`).

**Comment by Lumrenion** [comment]
In my non-profit organization, up until now we used a shared email account for everybody who should be allowed to access it (like info@myorganization.com). This has several issues - the utmost that when one person should not be allowed to access the account anymore, the password had to be changed and everybody had to change the password in their email programs.
Now what seems to be a solution to this issue is to install personal email accounts for every person and forward the emails from info@myorganization.com to those personal accounts. But then, nobody can send emails from the general purpose account.

If I am on a lost track with this approach, I am open for suggestions 😃 But currently, I would appreaciate if it was possible in the admin UI to select FROM addresses an account should be permitted to use (besides the account itself ofcourse).

**Comment by fracture-point** [comment]
@Lumrenion I don't think Mailu really supports the shared mailbox concept that you're looking for, but I can (off-topic) highly recommend using an org-wide password manager to solve the password issue.  We use the LastPass browser extension (I have no affiliation with them), and that helps in such situations because you can share the masked password with the users.  Bitwarden is also a solid option, though I don't have experience with it.

More on-topic, +1 for enabling FROM permission management in the admin UI.

**Comment by micw** [comment]
It should work as expected either with forward or with alias addresses (can't recall which one it was) - the user who gets the mail can send with that mail address.

**Comment by Lumrenion** [comment]
@micw I remember I have tried it like a year ago with alias and it did not work. Back then I did not dig deeper into that. I just gave the forward a try:
1. create new email account (actualAccont@tld.com)
2. have one email account forward messages to the new one (forwardAccount@tld.com)
3. have another email account NOT forwarding messages to the new one (noForwardAccount@tld.com)
4. Login with actualAccount@tld.com at rainloop webmail
5. Add Aliases forwardAccount@tld.com and noForwardAccount@tld.com
6. Try to sending three emails from actualAccount@tld.com with those three senders
7. Sending with the first and second works. Sending with the third does not. Just as expected!

It is not that self explaining as you can forward emails to external mail addresses (like actualAccount@gmail.com) as well. That feature is not documented anywhere, is it? 
Thank you very much! This solves my problem perfectly.

**Comment by archont00** [comment]
Mailu 1.7 here.
Thanks for the great write up - helpful to migrate my existing setup to Mailu.

I am not able to relay messages unless I unset:
```
virtual_mailbox_maps = ${podop}mailbox
```
to
```
virtual_mailbox_maps = 
```
The error message is:
```
Mar 29 20:02:15 mailu postfix/smtpd[3085]: NOQUEUE: reject: RCPT from my.lan.hostname[10.11.13.23]: 550 5.1.0 <identity1@external.com>: Sender address rejected: User unknown in virtual mailbox table; from=<identity1@external.com> to=<somebody@example.org> proto=ESMTP helo=<[10.11.13.23]>
```
Via admin interface, I created `mydomain.net` and a user `user@mydomain.net`.
I relay all messages via smtp servers of external mail providers and use fetchmail to get incoming messages to my Mailu imap server.

Is the `virtual_mailbox_maps` important in my setup?

**Comment by nextgens** [comment]
I've implemented what @pirate suggested in #1904

I am not convinced that we want to support narrower configurations (where a user is allowed but only for specific aliases)... those that need it can use overrides.

**Comment by daumling** [comment]
To add to this issue (despite having been closed): I wanted only the logged in user plus info and support as the allowed senders.

```
/overrides/postfix/postfix.cf:
smtpd_sender_login_maps = unionmap:{socketmap:unix:/tmp/podop.socket:senderlogin, regexp:/overrides/sender_logins}
/overrised/postfix/sender_logins:
/info@maydomain.com/ OK
/support@domain.com/ OK
```

**Comment by miroslavskela** [comment]
Hello,
I have problem with this setting. Have implemented everything in /mailu/data/overrides, and also after that didn't work moved to /mailu/overrides, but still cant sent mail even as another user on same mail server, with same domain.Does anyone have some idea what could be problem. sender_logins and sasl_passwd are empty. Using nodemailer smtp transport, which is working when sending as authenticated user. Thank you!

**Comment by JasperAH** [comment]
Thanks for the writeup!

It did not work out-of-the box for me because of the following (I wondered why):
> 
> ```
> /.*/                      admin@mydomain.com
> /.^*@otherdomain.com/     admin@otherdomain.com
> ```

Changing to `/^.*@otherdomain.com/` did the trick for me :)

**Comment by pirate** [comment]
Your fix is right, where did you see that `.^*@...` typo originally @JasperAH? I can go correct it.

**Comment by archont00** [comment]
@fracture-point 
Not sure what has changed, but after ugrade from Mailu 1.7 to 1.9, the multiple relaying setup as per sender's address as described in this bug has stopped working.

It seems that mailu modifies the Sender field from: `user1@hotmail.com` to `SRS0=cOgo=WT=hotmail.com=user1@mydomain.com`:

```
$ cat /overrides/postfix.cf | grep 'sender_login'
smtpd_sender_login_maps = unionmap:{socketmap:unix:/tmp/podop.socket:senderlogin, pcre:/overrides/sender_logins.map}
```

```log
Jun 12 10:13:47 tiger mailu_smtp[1108]: INFO:root:Connect 
Jun 12 10:13:47 tiger mailu_smtp[1108]: DEBUG:root:Received bytearray(b'sendermap user1@hotmail.com')
Jun 12 10:13:47 tiger mailu_smtp[1108]: DEBUG:root:Request sendermap/user1@hotmail.com
Jun 12 10:13:47 tiger mailu_smtp[1108]: DEBUG:root:Table get user1@hotmail.com
Jun 12 10:13:47 tiger mailu_admin[1108]: 172.17.31.6 - - [12/Jun/2022:10:13:47 +0200] "GET /internal/postfix/sender/map/hidden@hotmail.com HTTP/1.1" 200 47 "-" "Python/3.9 aiohttp/3.8.1"
Jun 12 10:13:47 tiger mailu_smtp[1108]: DEBUG:root:Table get user1@hotmail.com is SRS0=cOgo=WT=hotmail.com=user1@mydomain.com
Jun 12 10:13:47 tiger mailu_smtp[1108]: DEBUG:root:Replying b'OK SRS0=cOgo=WT=hotmail.com=user1@mydomain.com'
Jun 12 10:13:47 tiger mailu_smtp[1108]: DEBUG:root:Received bytearray(b'sendermap SRS0=cOgo=WT=hotmail.com=user1@mydomain.com')
```
And then relaying fails since I have no map in `/overrides/sasl_passwd.map` for such a sender.

When I modify `/overrides/sasl_passwd.map` to have a 'catch all' map for Mailgun like:
```
hidden@hotmail.com         hidden@hotmail.com:hiddenapppassword
[smtp.eu.mailgun.org]:587 admin@mydomain.net:some_long_password
```
Then the e-mail from `user1@hotmail.com` gets relayed via Mailgun.

Sender field is `user1=hotmail.com@mydomain.com` and From field remains `user1@hotmail.com`.

Any idea why `user1@hotmail.com` gets modified to `user1=hotmail.com@mydomain.com`? Has Mailu been updated to deal with sender dependent authentication for SMTP relaying differently?

P.S. Something like sender address re-writing takes place? 
http://www.postfix.org/ADDRESS_REWRITING_README.html#canonical

**Comment by nextgens** [comment]
The envelope sender is rewritten by SRS (see https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme)
The idea being that your Mailu installation is not authorized to send emails as @hotmail.com  ... as for whether it breaks things to disable it... the answer is "maybe".

Without SRS any delivery problem will be reported to the Return-Path (that is hotmail's servers).

**Comment by bpawel-bclub** [comment]
Hi, this thread is very helpful, however, I have a question:
Can I relay emails through the same server (Postmark in this case) but depending on the domain of the sender, through their different servers? That means all relay_hosts are [smtp.postmarkapp.com] but passwords will be different for each domain. Is there a way to differentiate that? Thanks!

**Comment by nextgens** [comment]
Not without overriding postfix's configuration. This isn't the right place to talk about it
