### ISSUE TITLE
Error Creating DH params

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#275]
I'm testing the refactor-nginx  branch and seeing this error.

```
Creating DH params
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
...........................................................................................+......Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 177, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 19, in admin
    db.session.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
.    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
.    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.email [SQL: 'INSERT INTO user (created_at, updated_at, comment, localpart, password, quota_bytes, global_admin, enable_imap, enable_pop, forward_enabled, forward_destination, forward_keep, reply_enabled, reply_subject, reply_body, displayed_name, spam_enabled, spam_threshold, domain_name, email) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('2017-09-27', None, None, 'root', '{SHA512-CRYPT}$6$rounds=656000$WgOqCDXyy.Z67hqr$gJ5RWYNMSxkoqHMOvXwfmMIiBV6Jy0iJGgJ75qI6HyORQci7Mk9WL5NbUT0MB72NAVhA772qv79MLXuL1QMCY.', 1000000000, 1, 1, 1, 0, None, 1, 0, None, None, '', 1, 80.0, 'example.net', 'root@example.net')]
......................................................+............................................................................................................................................................................................................+................+.......................+.........................................+.........................................................................................................................................+............................................................+............................................+..............................................................................................+................................................................................................................................................................................................................................+..................................................................................................................+...................................................................................................................................................................................................................................................+..............+.+........................................................................................................+.......................................................................................................................................+........................................................................................................................................................................................................................................................................................................................................................+.......................................................................................................................................+.................................................................................................................................................................................................................+.....................................................+............................................................................................................................................................................................+...............................................................................................................+.........................................+....................................................................................................................................+..............................................................................................................................................+........................................................................................................................................................................+........................................................................................................+........................................................................................................................................................................+.......................................+..................................................................................................................................................................+.........+...............................................................................+.............................................................................................+...........................................................................................................+......................................................................................................................................................+.......................................................................................+...............................+................................................+......................................................................................................................+........................................................................................................................................................................+..........+.............................................................................+..............+.............+.......................................................................................................................................................................................................................................................+...........+.......................................................................+....................+....................................................................................................................................................................................................................................+...................................................................+..................................+......................................................................................................................................................................................+..........................................................................+..........................................................................................................................+................................+...................................................................................................................................+................................................................................+.................................................................................................................................................................................................................................+.........................................................................................+...................................................................+..............+.........................................................................................................+.........................................................+....................+........+.............+............................+..............................................................................................+..........................................................................+..................................................................+.......................................................................................+................................................................................................................................+............................................................................................................................................................+....................................................................+..........................................................................................................................................................................................+................................................................................................................+.......+............................................................+.................................................................................+...................................................................+.......................................................................................................................................................................................................................+......................................................................+.+......+.........................................................................................++*++*
/certs/dhparam.pem: No such file or directory
Reloading services using TLS
```

**Comment by kaiyou** [comment]
This sounds like you either have not updated your `docker-compose.yml` or have not pulled the proper version for the admin container.

**Comment by SaiGonSeamus** [comment]
Yeah, it was set to stable by accident.

All comes up now except can't access the admin or webmail. 
![image](https://user-images.githubusercontent.com/7721269/30956749-7aca965c-a462-11e7-8c94-f89f481040f2.png)

In the logs this is the only thing I see that looks relevant

`front_1 | nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:46`

**Comment by kaiyou** [comment]
Did you load the latest `.env`, including the `WEB_ADMIN` and `WEB_WEBMAIL` configuration directives?

**Comment by SaiGonSeamus** [comment]
Yes, I did. This server is running in a DMZ with newly generated self-signed certs.

**Comment by kaiyou** [comment]
Could you dump the generated nginx configuration then?

```
docker-compose exec front cat /etc/nginx/nginx.conf
```

**Comment by SaiGonSeamus** [comment]
`ERROR: Container 8f864971ff777b4a53ef17fcc60c5a702ee0cfcbc5c04465031fc5cee330641f is restarting, wait until the container is running`

**Comment by kaiyou** [comment]
Aha, of course. Then:

```
docker-compose run --rm front sh -c '/config.py; cat /etc/nginx/nginx.conf'
```

**Comment by SaiGonSeamus** [comment]
Where myhostname.mydomainname.com replaces my real values.

```
#  Basic configuration
user nginx;
worker_processes 4;
error_log /dev/stderr info;
pid /var/run/nginx.pid;
load_module "modules/ngx_mail_module.so";

events {
    worker_connections  1024;
}

http {
    # Standard HTTP configuration with slight hardening
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    keepalive_timeout  65;
    server_tokens off;
    absolute_redirect off;

    server {
      listen 80;

      # TLS configuration
      
      listen 443 ssl;
      include /etc/nginx/tls.conf;
      ssl_session_cache shared:SSLHTTP:50m;
      add_header Strict-Transport-Security max-age=15768000;

      if ($scheme = http) {
        return 301 https://$host$request_uri;
      }
      

      

      # Actual logic
      
      
      location / {
        return 301 $scheme://$host/webmail/;
      }

      location  {
        rewrite ^/(.*) /$1 break;
        proxy_pass http://webmail;
      }
      

      
      location  {
        return 301 /ui;
      }
      location ~ /(ui|static) {
        rewrite ^/(.*) /$1 break;
        proxy_set_header X-Forwarded-Prefix ;
        proxy_pass http://admin;
      }
      

      
      location /webdav {
        rewrite ^/webdav/(.*) /$1 break;
        proxy_pass http://webdav:5232;
      }
      
      
    }
}

mail {
    server_name myhostname.mydomainname.com;
    auth_http http://172.18.0.7/internal/nginx;
    proxy_pass_error_message on;

    
    include /etc/nginx/tls.conf;
    ssl_session_cache shared:SSLMAIL:50m;
    

    server {
      listen 25;
      
      starttls on;
      
      protocol smtp;
      smtp_auth none;
    }

    
    server {
      listen 143;
      
      starttls only;
      
      protocol imap;
      imap_auth plain;
    }

    
    server {
      listen 465 ssl;
      protocol smtp;
      smtp_auth plain;
    }

    server {
      listen 597;
      starttls only;
      protocol smtp;
      smtp_auth plain;
    }

    server {
      listen 993 ssl;
      protocol imap;
      imap_auth plain;
    }
    
    
}
```

**Comment by SaiGonSeamus** [comment]
```
# Mailu main configuration file
#
# Most configuration variables can be modified through the Web interface,
# these few settings must however be configured before starting the mail
# server and require a restart upon change.

###################################
# Common configuration variables
###################################

# Set this to the path where Mailu data and configuration is stored
ROOT=/mailu

# Mailu version to run (stable, 1.0, 1.1, etc. or latest)
VERSION=refactor-nginx

# Set to a randomly generated 16 bytes string
SECRET_KEY=xxxxxxxxxxxxxxxx

# Address where listening ports should bind
BIND_ADDRESS=myinternalip

# Main mail domain
DOMAIN=mydomainname.com

# Hostnames for this server, separated with comas
HOSTNAMES=myhostname.mydomainname.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls)
TLS_FLAVOR=cert

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=rainloop

# Dav server implementation (value: radicale, none)
WEBDAV=radicale

# Antivirus solution (value: clamav, none)
ANTIVIRUS=clamav

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions, make sure that you include your Docker
# internal network (default to 172.17.0.0/16)
RELAYNETS=172.16.0.0/12

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
# e.g. localpart+custom@domain;tld
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

###################################
# Web settings
###################################

# Path to the admin interface if enabled
WEB_ADMIN = /admin

# Path to the webmail if enabled
WEB_WEBMAIL = /webmail

###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
PASSWORD_SCHEME=SHA512-CRYPT

```

**Comment by kaiyou** [comment]
Sorry, but I see no reason why this would not work, then. Could you also display `/conf/nginx.conf` from inside the container, maybe it is corrupted in some way or you do not have the proper version?

**Comment by kaiyou** [comment]
Ah. Spaces around your `=` signs in `.env` for `WEB_ADMIN` and `WEB_WEBMAIL`. This is a temporary version that I pushed, I thought I fixed it.

**Comment by SaiGonSeamus** [comment]
No, that's didn't fix it. nginx error of before is gone but still no admin or webmail. Only error I can see in the logs is this.

```
fetchmail_1  | Traceback (most recent call last):
antispam_1   | 2017-09-28 20:01:44 #14(normal) <4wnnyn>; cfg; rspamd_sqlite3_init: enable per language statistics for BAYES_HAM
antispam_1   | 2017-09-28 20:01:44 #13(normal) <35rhob>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/mid.inc
redis_1      | 1:M 28 Sep 20:01:43.665 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
fetchmail_1  |   File "/fetchmail.py", line 90, in <module>
antispam_1   | 2017-09-28 20:01:44 #14(normal) <o6xehe>; map; rspamd_map_file_check_callback: old mtime is -1, new mtime is 1501102039 for map file /etc/rspamd/2tld.inc
antispam_1   | 2017-09-28 20:01:44 #14(normal) <o6xehe>; map; rspamd_map_file_read_callback: rereading map file /etc/rspamd/2tld.inc
redis_1      | 1:M 28 Sep 20:01:43.665 * Ready to accept connections
fetchmail_1  |     run(connection, cursor, debug)
antispam_1   | 2017-09-28 20:01:44 #14(normal) <o6xehe>; map; read_map_file: /etc/rspamd/2tld.inc: read map dat, 8213 bytes
antispam_1   | 2017-09-28 20:01:44 #12(normal) <hhqhwh>; map; rspamd_map_file_read_callback: rereading map file /var/lib/rspamd/surbl-whitelist.inc.local
fetchmail_1  |   File "/fetchmail.py", line 44, in run
fetchmail_1  |     """)
fetchmail_1  | sqlite3.OperationalError: no such table: fetch
fetchmail_1  | Traceback (most recent call last):
fetchmail_1  |   File "/fetchmail.py", line 90, in <module>
fetchmail_1  |     run(connection, cursor, debug)
fetchmail_1  |   File "/fetchmail.py", line 44, in run
fetchmail_1  |     """)
fetchmail_1  | sqlite3.OperationalError: no such table: fetch
fetchmail_1  | Traceback (most recent call last):
fetchmail_1  |   File "/fetchmail.py", line 90, in <module>
fetchmail_1  |     run(connection, cursor, debug)
fetchmail_1  |   File "/fetchmail.py", line 44, in run
fetchmail_1  |     """)
fetchmail_1  | sqlite3.OperationalError: no such table: fetch
fetchmail_1  | Traceback (most recent call last):
fetchmail_1  |   File "/fetchmail.py", line 90, in <module>
fetchmail_1  |     run(connection, cursor, debug)
fetchmail_1  |   File "/fetchmail.py", line 44, in run
fetchmail_1  |     """)
fetchmail_1  | sqlite3.OperationalError: no such column: keep
```

**Comment by kaiyou** [comment]
This is a fetchmail issue, don't you have proper `nginx` logs now? could you dump your nginx config one more time?

Also, regarding Fetchmail, it simply looks like it started before the database was completely created by the admin container. I would have to fix the race condition to avoid polluting logs, but it should not have any impact.

**Comment by SaiGonSeamus** [comment]
```
 docker-compose run --rm front sh -c '/config.py; cat /etc/nginx/nginx.conf'
nginx: [error] open() "/var/run/nginx.pid" failed (2: No such file or directory)
#  Basic configuration
user nginx;
worker_processes 4;
error_log /dev/stderr info;
pid /var/run/nginx.pid;
load_module "modules/ngx_mail_module.so";

events {
    worker_connections  1024;
}

http {
    # Standard HTTP configuration with slight hardening
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    keepalive_timeout  65;
    server_tokens off;
    absolute_redirect off;

    server {
      listen 80;

      # TLS configuration
      
      listen 443 ssl;
      include /etc/nginx/tls.conf;
      ssl_session_cache shared:SSLHTTP:50m;
      add_header Strict-Transport-Security max-age=15768000;

      if ($scheme = http) {
        return 301 https://$host$request_uri;
      }
      

      

      # Actual logic
      
      
      location / {
        return 301 $scheme://$host/webmail/;
      }

      location /webmail {
        rewrite ^/webmail/(.*) /$1 break;
        proxy_pass http://webmail;
      }
      

      
      location /admin {
        return 301 /admin/ui;
      }
      location ~ /admin/(ui|static) {
        rewrite ^/admin/(.*) /$1 break;
        proxy_set_header X-Forwarded-Prefix /admin;
        proxy_pass http://admin;
      }
      

      
      location /webdav {
        rewrite ^/webdav/(.*) /$1 break;
        proxy_pass http://webdav:5232;
      }
      
      
    }
}

mail {
    server_name leningrad.saigonsecure.com;
    auth_http http://172.18.0.8/internal/nginx;
    proxy_pass_error_message on;

    
    include /etc/nginx/tls.conf;
    ssl_session_cache shared:SSLMAIL:50m;
    

    server {
      listen 25;
      
      starttls on;
      
      protocol smtp;
      smtp_auth none;
    }

    
    server {
      listen 143;
      
      starttls only;
      
      protocol imap;
      imap_auth plain;
    }

    
    server {
      listen 465 ssl;
      protocol smtp;
      smtp_auth plain;
    }

    server {
      listen 597;
      starttls only;
      protocol smtp;
      smtp_auth plain;
    }

    server {
      listen 993 ssl;
      protocol imap;
      imap_auth plain;
    }
    
    
}
```
front logs are just the DH generation.

This is webmail
```
webmail_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.10. Set the 'ServerName' directive globally to suppress this message
webmail_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.10. Set the 'ServerName' directive globally to suppress this message
webmail_1    | [Thu Sep 28 20:01:45.545495 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.31 configured -- resuming normal operations
webmail_1    | [Thu Sep 28 20:01:45.545570 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by kaiyou** [comment]
And what does `curl -v https://yourserver.tld/admin/` return exactly?

**Comment by SaiGonSeamus** [comment]
Times out from the LAN, refused from an expernal VPN, it's passing the firewall ok.

```
$ curl -v https://myhostname.mydomainname.com/admin/
*   Trying myexternalip...
* TCP_NODELAY set
* Connection failed
* connect to myexternalip port 443 failed: Operation timed out
* Failed to connect to myhostname.mydomainname.com port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to myhostname.mydomainname.com port 443: Operation timed out

$ curl -v https://myhostname.mydomainname.com/admin/
*   Trying myexternalip...
* TCP_NODELAY set
* Connection failed
* connect to myexternalip port 443 failed: Connection refused
* Failed to connect to myhostname.mydomainname.com port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to myhostname.mydomainname.com port 443: Connection refused
```

**Comment by kaiyou** [comment]
Now this sounds either like : 
- the front container is still not starting, could you check, maybe delete and recreate it
- some unrelated firewalling/routing/whatever issue

**Comment by SaiGonSeamus** [comment]
I'll bring refactor-nginx up on my cloud box to rule out FW/Routing issue and get back to you. Thanks for the help so far.

**Comment by SaiGonSeamus** [comment]
OK, I've tried it on my cloud server with both letsencrypt and cert options using a different domain name that was previously working on this server with letsencrypt with traefik. Both were clean attemptes with fresh pulls, all previous images etc deleted Both with the same results as on the DMZ server. Again nothing in nginx logs.

I saw this on the Letsencrypt attempt, it did not generate any certs or a dhparams.pem

```
smtp_1       | Traceback (most recent call last):
smtp_1       |   File "/start.py", line 12, in <module>
smtp_1       |     os.environ["FRONT_ADDRESS"] = socket.gethostbyname("front")
smtp_1       | socket.gaierror: [Errno -2] Name does not resolve
smtp_1       | rsyslogd:  [origin software="rsyslogd" swVersion="8.26.0" x-pid="6" x-info="http://www.rsyslog.com"] start
smtp_1       | postfix/master[108]: daemon started -- version 3.1.4, configuration /etc/postfix
```

These are the nginx logs from the cert attempt.

```
webmail_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
webmail_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.2. Set the 'ServerName' directive globally to suppress this message
webmail_1    | [Fri Sep 29 10:11:42.942535 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.31 configured -- resuming normal operations
webmail_1    | [Fri Sep 29 10:11:42.942607 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
root@mail:/mailu# docker-compose logs front
Attaching to mailu_front_1
front_1      | Generating DH parameters, 4096 bit long safe prime, generator 2
front_1      | This is going to take a long time
```

**Comment by SaiGonSeamus** [comment]
This is now working on our DMZ server with self-signed cert with the latest code. :)
