### ISSUE TITLE
Demonstration server - Admin credentials do not seem to work.

### ISSUE THREAD

**Issue by d19dotca** [Mailu/Mailu#987]
Hello,

I've been trying to use the Mailu demo server for checking out features and stuff and familiarizing myself with it before deploying it in my Docker environment. Unfortunately for several days now I have been unable to login with the credentials provided in the documentation. Can anyone please double-check this and reset if necessary?

From the docs:

Server name : test.mailu.io
IP address : 173.249.45.89
Webmail : https://test.mailu.io/webmail/
Admin UI : https://test.mailu.io/admin/
Admin login : admin@test.mailu.io
Admin password : letmein

**Comment by glaszig** [comment]
problem persists. can somebody check or update the docs? thanks.

**Comment by kaiyou** [comment]
We are currently trying to get in touch with people managing that test server. Otherwise we will setup a new one in the coming weeks.

**Comment by fightchwang** [comment]
anybody contribute a practical username/password to login webmail? cause the credentials of admin seems not working. thx so much

**Comment by Nebukadneza** [comment]
Hi,
we’ll try to set up a new server under the control of the currently active people soon. Please have some patience, and sorry for the delay!

**Comment by muhlemmer** [comment]
Sorry about that guys, the demo server has been reset.

It seems the daily Cron job is not firing somehow.

**Comment by muhlemmer** [comment]
Ok, the cron seemed to be defined in the wrong place. That is fixed now also. It should reset every night at 03:00 utc

**Comment by glaszig** [comment]
well, still cannot log into the [admin panel](https://test.mailu.io/admin/ui/login) with the [credentials provided](https://mailu.io/1.6/demo.html).

<img width="352" alt="Bildschirmfoto 2019-07-07 um 12 33 06" src="https://user-images.githubusercontent.com/201135/60771272-6aa06f00-a0b3-11e9-98ad-6e7acf776050.png">

**Comment by muhlemmer** [comment]
Ok, double checked and the cron job for resetting worked fine last night at 3 AM. I will close this issue now.

**Comment by muhlemmer** [comment]
@glaszig, sorry completely missed your post. The thing is, after a reset the credentials work fine. I've checked in numerous times. I think someone is dicking around and changing the password all the time.

**Comment by hoellen** [comment]
@muhlemmer Since #1067 is merged, can you please set a reset of the credentials every few minutes?
We receive continuous feedback about wrong access data. Thanks.

**Comment by muhlemmer** [comment]
Yeah, that's done since so time now. Closing...

https://github.com/Mailu/infra/blob/6fd2f8db3cdb42a9d7bd80af3dce5dec8125eaf9/crontab#L16

**Comment by tomaswarynyca** [comment]
It is impossible to access the demo :/
Incorrect username or password
